### ISSUE TITLE
Improve details interface & API documentation

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-java#1]
To make Details more easy to use, we should simply overload the addDetail methods with all concrete possibilities that can be added:
- addDetail(key, String);
- addDetail(key, Details);
- addDetail(key, ObjectDescription);
- addDetail(key, ObjectReference)
- addDetail(key, ObjectTreeNode)
- addDetail(key, ObjectList)

Each of this methods should be documentated appropriately with Javadoc, to inform the user roughly about when to use which of these variants. This would help scenarioo users allready a lot.

Also the C# writer library should be improved accordingly (open issue, when realising this in Java!).

**Comment by danielsuter** [comment]
@bruderol Does it actually make sense to nest a details object? Shouldn't an ObjectTreeNode be used?
