### ISSUE TITLE
Can't build: Execution failed for task ':signArchives'

### ISSUE THREAD

**Issue by cgrossde** [scenarioo/scenarioo-java#10]
**Summary:** Can't build locally after checking out the project

**Steps to reproduce:**

- Checkout `scenarioo-java`
- Execute `./gradlew clean build` 

**Expected result:** Successful build

**Actual result:**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory
```

**Comment by bruderol** [comment]
@cgrossde thanks for opening the issue! let's quickly synch today what to do about this?
