### ISSUE TITLE
Update Gradle to 4.7

### ISSUE THREAD

**Issue by davidlahner** [scenarioo/scenarioo-java#12]
The current Gradle version (3.3) is not Java 9 compatible. This means a Java JDK 8 version is needed on the developer machine to run Gradle tasks for Scenarioo.

Updating the Gradle Wrapper to the latest stable version 4.7 gives us more flexibility in the future and allows for a quicker start for new developers.

see also: https://github.com/scenarioo/scenarioo/issues/680

**Comment by bruderol** [comment]
Thanks - I merged it
