### ISSUE TITLE
Support Java > 7

### ISSUE THREAD

**Issue by dola** [scenarioo/scenarioo-java#2]
Currently scenarioo-java can not be used with Java versions after 7.
Most likely it would suffice to update all dependencies to fix this.

**Comment by bruderol** [comment]
this is not true. The library can be used with java 8.
Only it can not be developed with versions after 7.

But yes, we should fix that, to upgrade to version 8 for version 3.x

**Comment by danielsuter** [comment]
Our CI runs with java 8 and the client runs there properly, so I don't see any problem.

**Comment by bruderol** [comment]
@dola do you agree we can close it?

**Comment by bruderol** [comment]
@dola I close, can you please reopen and give more precise information about your problem, if you still have it. Thanks.
