### ISSUE TITLE
Prepare scenarioo-java for maven central

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo-java#4]

**Comment by danielsuter** [comment]
Please review #5 @bruderol @adiherzog

**Comment by bruderol** [comment]
I merged the PRs  and updated docu, see the already merged PRs.

What is missing now, that we can close this (or did I miss something?):
* Solve the problem that developers must be able to build without needing the certificates (see email)

* Release once again to maven central including the new licence in maven meta data (new version number!)
* do not forget to follow the full release process as documented - including merge to master and putting the release with release notes on the github releases page.
* Once released adjust `scenarioo` to use the newest version directly from maven central and adjust developer docu accordingly: currently the server dev docu still says that one needs to checkout this repo and build it, but if we directly link to latest version from maven central, this would not be needed anymore and one would just have to change the dependency to appropriate snapshot version when he wants to do changes in the library. @danielsuter what you think?

**Comment by bruderol** [comment]
@danielsuter whats the state with this??  Can we close this or is anything missing from my last comments?
